runtime: go
api_version: go1

env_variables:
  CLIENT_ID: 65587295914-kbl4e2chuddg9ml7d72f6opqhddl62fv.apps.googleusercontent.com
  CLIENT_SECRET: 0NjL7OoLyGYiZkTUKjzifqjd

handlers:
- url: /.*
  script: _go_app